Task 4
polinapanchenko/Coding-Girls-2018 pull request #2
Opened 2018-07-22 10:40 UTC by polinapanchenko

- header, main and footer added to the html body;
- images added;
- textes added.

2018-07-22 12:20 UTC, Afelua requested changes

2018-07-22 12:20 UTC, Afelua commented on index.html
> +						<img src="./images/fb.png" alt="">
Картинка должна находится внутри тега а, иначе картинка как ссылка не будет работать.

2018-07-23 04:25 UTC, polinapanchenko commented on index.html
> +						<img src="./images/fb.png" alt="">
Елена, спасибо за комментарий, это упустила.
Поправила для соцсетей, а также для картинок arrow, которые идут после ссылок в зеленом блоке из 4 частей, чтобы все это потом стало единой ссылкой.

2018-07-23 12:43 UTC, Afelua approved these changes

2018-07-24 18:26 UTC, merged